In [3]:
#a
import numpy as np
arr=np.array([1,2,3,6,4,5])
print("reversed:",arr[::-1])

reversed: [5 4 6 3 2 1]


In [4]:
#b
arr1= np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(" flatten :",arr1.flatten())
print("flatten using ravel()",arr1.ravel())

 flatten : [1 2 3 2 4 5 1 2 3]
flatten using ravel() [1 2 3 2 4 5 1 2 3]


In [5]:
#c
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]])
print(np.array_equal(arr1,arr2))


True


In [8]:
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent(arr):
    vals,counts=np.unique(arr,return_counts=True)
    max_count=np.max(counts)
    max_val=vals[counts.argmax()]
    indices=np.where(arr==max_val)[0]
    return max_val,indices
print("most frequent",most_frequent(x))
print("most frequent",most_frequent(y))

most frequent (np.int64(1), array([0, 5, 7, 8, 9]))
most frequent (np.int64(1), array([0, 1, 2]))


In [10]:
#e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("total sum",gfg.sum())
print("row wise sum:",gfg.sum(axis=1))
print("column wise",gfg.sum(axis=0))


total sum 45
row wise sum: [[14]
 [16]
 [15]]
column wise [[20  9 16]]


In [11]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("diagonal sum ",np.trace(n_array))
eig_vals,eig_vecs=np.linalg.eig(n_array)
print(eig_vals)
print(eig_vecs)
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

diagonal sum  176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [13]:
#g
p =np.array([[1, 2], [2, 3]]) 
q = np.array([[4, 5], [6, 7]])
print(np.dot(p,q))
print(np.cov(p,rowvar=False))
p2 =np.array ([[1, 2], [2, 3], [4, 5]]) 
q2= np.array([[4, 5, 1], [6, 7, 2]])  
print(np.dot(p2,q2))
print(np.cov(p2,rowvar=False))

[[16 19]
 [26 31]]
[[0.5 0.5]
 [0.5 0.5]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.33333333 2.33333333]
 [2.33333333 2.33333333]]


In [14]:
#h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print(np.outer(x.flatten(),y.flatten()))
cartesian=np.array(np.meshgrid(x.flatten(),y.flatten())).T.reshape(-1,2)
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [17]:
# que2 
array = np.array([[1, -2, 3],[-4, 5, -6]])

# (a)
print("Absolute:\n", np.abs(array))
flat = array.flatten()
print("25th percentile:", np.percentile(flat, 25))
print("50th percentile:", np.percentile(flat, 50))
print("75th percentile:", np.percentile(flat, 75))

print("Row-wise percentile:\n", np.percentile(array, [25, 50, 75], axis=1))
print("Column-wise percentile:\n", np.percentile(array, [25, 50, 75], axis=0))

print("Mean:", flat.mean())
print("Median:", np.median(flat))
print("Std Dev:", np.std(flat))

# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceiling:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Rounded:", np.round(a))


Absolute:
 [[1 2 3]
 [4 5 6]]
25th percentile: -3.5
50th percentile: -0.5
75th percentile: 2.5
Row-wise percentile:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Column-wise percentile:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Mean: -0.5
Median: -0.5
Std Dev: 3.8622100754188224
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [18]:
#que3 
array = np.array([10, 52, 62, 16, 16, 54, 453])
print( np.sort(array))
print( np.argsort(array))
print( np.sort(array)[:4])
print(np.sort(array)[-5:])

array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array2[array2 == array2.astype(int)]
floats = array2[array2 != array2.astype(int)]
print("Integers:", ints)
print("Floats:", floats)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]
Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]


In [20]:

from PIL import Image
import numpy as np


def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
        print("Saved as grayscale_image.txt")
    else:
      
        for i in range(arr.shape[2]):
            np.savetxt(f"rgb_channel_{i}.txt", arr[:,:,i], fmt='%d')
        print("Saved as RGB image text files")

def load_text_file(filename):
    return np.loadtxt(filename)


